
[[language]]
name="html"
language-servers = [ "vscode-html-language-server", "tailwindcss-ls"]

[[language]]
name="jsx"
language-servers = [ "typescript-language-server", "tailwindcss-ls"]

[[language]]
name="tsx"
language-servers = [ "typescript-language-server", "tailwindcss-ls"]

[[language]]
name="svelte"
language-servers = [ "svelteserver", "tailwindcss-ls"]

[[language]]
name="python"
language-servers = [ "pyright" ]

[[language]]
name="markdown"
language-servers = [ "marksman"]
